//! Objeto Math

let resultado;

resultado = Math.PI;
resultado = Math.round(2.2); //! Redondea hacia arriba desde 6 en adelante
resultado = Math.ceil(2.2); //! Siempre redondea hacia arriba
resultado = Math.floor(2.2); //! Siempre redondea hacia abajo
resultado = Math.sqrt(244); //! Raíz cuadrada
resultado = Math.abs(244); //! Numero positivo lo convierte a negativo
resultado = Math.min(1,2,3,4,5,6); //! Toma el menor numero
resultado = Math.max(1,2,3,4,5,6); //! Toma el mayor numero
resultado = Math.random(); //! Retorna un numero al azar
resultado = Math.floor(Math.random() * 30); //! Retorna un numero al azar




console.log(resultado);